/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.chamcong.model.impl;

import com.liferay.docs.chamcong.model.Calamviec;
import com.liferay.docs.chamcong.model.CalamviecModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Calamviec service. Represents a row in the &quot;_Calamviec&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CalamviecModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CalamviecImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CalamviecImpl
 * @generated
 */
@JSON(strict = true)
public class CalamviecModelImpl
	extends BaseModelImpl<Calamviec> implements CalamviecModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a calamviec model instance should use the <code>Calamviec</code> interface instead.
	 */
	public static final String TABLE_NAME = "_Calamviec";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.INTEGER}, {"tencalamviec", Types.VARCHAR},
		{"gio_vao_chieu", Types.VARCHAR}, {"gio_ra_chieu", Types.VARCHAR},
		{"vao_truoc_chieu", Types.INTEGER}, {"ra_sau_chieu", Types.INTEGER},
		{"gio_vao_toi", Types.VARCHAR}, {"gio_ra_toi", Types.VARCHAR},
		{"vao_truoc_toi", Types.INTEGER}, {"ra_sau_toi", Types.INTEGER},
		{"gio_vao_sang", Types.VARCHAR}, {"gio_ra_sang", Types.VARCHAR},
		{"vao_truoc_sang", Types.INTEGER}, {"ra_sau_sang", Types.INTEGER},
		{"created_at", Types.TIMESTAMP}, {"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("tencalamviec", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("gio_vao_chieu", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("gio_ra_chieu", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("vao_truoc_chieu", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ra_sau_chieu", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("gio_vao_toi", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("gio_ra_toi", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("vao_truoc_toi", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ra_sau_toi", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("gio_vao_sang", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("gio_ra_sang", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("vao_truoc_sang", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ra_sau_sang", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table _Calamviec (id_ INTEGER not null primary key,tencalamviec VARCHAR(75) null,gio_vao_chieu VARCHAR(75) null,gio_ra_chieu VARCHAR(75) null,vao_truoc_chieu INTEGER,ra_sau_chieu INTEGER,gio_vao_toi VARCHAR(75) null,gio_ra_toi VARCHAR(75) null,vao_truoc_toi INTEGER,ra_sau_toi INTEGER,gio_vao_sang VARCHAR(75) null,gio_ra_sang VARCHAR(75) null,vao_truoc_sang INTEGER,ra_sau_sang INTEGER,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP = "drop table _Calamviec";

	public static final String ORDER_BY_JPQL = " ORDER BY calamviec.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY _Calamviec.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public CalamviecModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Calamviec.class;
	}

	@Override
	public String getModelClassName() {
		return Calamviec.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Calamviec, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Calamviec, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Calamviec, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Calamviec)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Calamviec, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Calamviec, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Calamviec)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Calamviec, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Calamviec, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Calamviec, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Calamviec, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Calamviec, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Calamviec, Object>>();
		Map<String, BiConsumer<Calamviec, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Calamviec, ?>>();

		attributeGetterFunctions.put("id", Calamviec::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<Calamviec, Integer>)Calamviec::setId);
		attributeGetterFunctions.put(
			"tencalamviec", Calamviec::getTencalamviec);
		attributeSetterBiConsumers.put(
			"tencalamviec",
			(BiConsumer<Calamviec, String>)Calamviec::setTencalamviec);
		attributeGetterFunctions.put(
			"gio_vao_chieu", Calamviec::getGio_vao_chieu);
		attributeSetterBiConsumers.put(
			"gio_vao_chieu",
			(BiConsumer<Calamviec, String>)Calamviec::setGio_vao_chieu);
		attributeGetterFunctions.put(
			"gio_ra_chieu", Calamviec::getGio_ra_chieu);
		attributeSetterBiConsumers.put(
			"gio_ra_chieu",
			(BiConsumer<Calamviec, String>)Calamviec::setGio_ra_chieu);
		attributeGetterFunctions.put(
			"vao_truoc_chieu", Calamviec::getVao_truoc_chieu);
		attributeSetterBiConsumers.put(
			"vao_truoc_chieu",
			(BiConsumer<Calamviec, Integer>)Calamviec::setVao_truoc_chieu);
		attributeGetterFunctions.put(
			"ra_sau_chieu", Calamviec::getRa_sau_chieu);
		attributeSetterBiConsumers.put(
			"ra_sau_chieu",
			(BiConsumer<Calamviec, Integer>)Calamviec::setRa_sau_chieu);
		attributeGetterFunctions.put("gio_vao_toi", Calamviec::getGio_vao_toi);
		attributeSetterBiConsumers.put(
			"gio_vao_toi",
			(BiConsumer<Calamviec, String>)Calamviec::setGio_vao_toi);
		attributeGetterFunctions.put("gio_ra_toi", Calamviec::getGio_ra_toi);
		attributeSetterBiConsumers.put(
			"gio_ra_toi",
			(BiConsumer<Calamviec, String>)Calamviec::setGio_ra_toi);
		attributeGetterFunctions.put(
			"vao_truoc_toi", Calamviec::getVao_truoc_toi);
		attributeSetterBiConsumers.put(
			"vao_truoc_toi",
			(BiConsumer<Calamviec, Integer>)Calamviec::setVao_truoc_toi);
		attributeGetterFunctions.put("ra_sau_toi", Calamviec::getRa_sau_toi);
		attributeSetterBiConsumers.put(
			"ra_sau_toi",
			(BiConsumer<Calamviec, Integer>)Calamviec::setRa_sau_toi);
		attributeGetterFunctions.put(
			"gio_vao_sang", Calamviec::getGio_vao_sang);
		attributeSetterBiConsumers.put(
			"gio_vao_sang",
			(BiConsumer<Calamviec, String>)Calamviec::setGio_vao_sang);
		attributeGetterFunctions.put("gio_ra_sang", Calamviec::getGio_ra_sang);
		attributeSetterBiConsumers.put(
			"gio_ra_sang",
			(BiConsumer<Calamviec, String>)Calamviec::setGio_ra_sang);
		attributeGetterFunctions.put(
			"vao_truoc_sang", Calamviec::getVao_truoc_sang);
		attributeSetterBiConsumers.put(
			"vao_truoc_sang",
			(BiConsumer<Calamviec, Integer>)Calamviec::setVao_truoc_sang);
		attributeGetterFunctions.put("ra_sau_sang", Calamviec::getRa_sau_sang);
		attributeSetterBiConsumers.put(
			"ra_sau_sang",
			(BiConsumer<Calamviec, Integer>)Calamviec::setRa_sau_sang);
		attributeGetterFunctions.put("created_at", Calamviec::getCreated_at);
		attributeSetterBiConsumers.put(
			"created_at",
			(BiConsumer<Calamviec, Date>)Calamviec::setCreated_at);
		attributeGetterFunctions.put("updated_at", Calamviec::getUpdated_at);
		attributeSetterBiConsumers.put(
			"updated_at",
			(BiConsumer<Calamviec, Date>)Calamviec::setUpdated_at);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalId() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("id_"));
	}

	@JSON
	@Override
	public String getTencalamviec() {
		if (_tencalamviec == null) {
			return "";
		}
		else {
			return _tencalamviec;
		}
	}

	@Override
	public void setTencalamviec(String tencalamviec) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tencalamviec = tencalamviec;
	}

	@JSON
	@Override
	public String getGio_vao_chieu() {
		if (_gio_vao_chieu == null) {
			return "";
		}
		else {
			return _gio_vao_chieu;
		}
	}

	@Override
	public void setGio_vao_chieu(String gio_vao_chieu) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gio_vao_chieu = gio_vao_chieu;
	}

	@JSON
	@Override
	public String getGio_ra_chieu() {
		if (_gio_ra_chieu == null) {
			return "";
		}
		else {
			return _gio_ra_chieu;
		}
	}

	@Override
	public void setGio_ra_chieu(String gio_ra_chieu) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gio_ra_chieu = gio_ra_chieu;
	}

	@JSON
	@Override
	public int getVao_truoc_chieu() {
		return _vao_truoc_chieu;
	}

	@Override
	public void setVao_truoc_chieu(int vao_truoc_chieu) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vao_truoc_chieu = vao_truoc_chieu;
	}

	@JSON
	@Override
	public int getRa_sau_chieu() {
		return _ra_sau_chieu;
	}

	@Override
	public void setRa_sau_chieu(int ra_sau_chieu) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ra_sau_chieu = ra_sau_chieu;
	}

	@JSON
	@Override
	public String getGio_vao_toi() {
		if (_gio_vao_toi == null) {
			return "";
		}
		else {
			return _gio_vao_toi;
		}
	}

	@Override
	public void setGio_vao_toi(String gio_vao_toi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gio_vao_toi = gio_vao_toi;
	}

	@JSON
	@Override
	public String getGio_ra_toi() {
		if (_gio_ra_toi == null) {
			return "";
		}
		else {
			return _gio_ra_toi;
		}
	}

	@Override
	public void setGio_ra_toi(String gio_ra_toi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gio_ra_toi = gio_ra_toi;
	}

	@JSON
	@Override
	public int getVao_truoc_toi() {
		return _vao_truoc_toi;
	}

	@Override
	public void setVao_truoc_toi(int vao_truoc_toi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vao_truoc_toi = vao_truoc_toi;
	}

	@JSON
	@Override
	public int getRa_sau_toi() {
		return _ra_sau_toi;
	}

	@Override
	public void setRa_sau_toi(int ra_sau_toi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ra_sau_toi = ra_sau_toi;
	}

	@JSON
	@Override
	public String getGio_vao_sang() {
		if (_gio_vao_sang == null) {
			return "";
		}
		else {
			return _gio_vao_sang;
		}
	}

	@Override
	public void setGio_vao_sang(String gio_vao_sang) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gio_vao_sang = gio_vao_sang;
	}

	@JSON
	@Override
	public String getGio_ra_sang() {
		if (_gio_ra_sang == null) {
			return "";
		}
		else {
			return _gio_ra_sang;
		}
	}

	@Override
	public void setGio_ra_sang(String gio_ra_sang) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_gio_ra_sang = gio_ra_sang;
	}

	@JSON
	@Override
	public int getVao_truoc_sang() {
		return _vao_truoc_sang;
	}

	@Override
	public void setVao_truoc_sang(int vao_truoc_sang) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_vao_truoc_sang = vao_truoc_sang;
	}

	@JSON
	@Override
	public int getRa_sau_sang() {
		return _ra_sau_sang;
	}

	@Override
	public void setRa_sau_sang(int ra_sau_sang) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ra_sau_sang = ra_sau_sang;
	}

	@JSON
	@Override
	public Date getCreated_at() {
		return _created_at;
	}

	@Override
	public void setCreated_at(Date created_at) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_created_at = created_at;
	}

	@JSON
	@Override
	public Date getUpdated_at() {
		return _updated_at;
	}

	@Override
	public void setUpdated_at(Date updated_at) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updated_at = updated_at;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Calamviec toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Calamviec>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CalamviecImpl calamviecImpl = new CalamviecImpl();

		calamviecImpl.setId(getId());
		calamviecImpl.setTencalamviec(getTencalamviec());
		calamviecImpl.setGio_vao_chieu(getGio_vao_chieu());
		calamviecImpl.setGio_ra_chieu(getGio_ra_chieu());
		calamviecImpl.setVao_truoc_chieu(getVao_truoc_chieu());
		calamviecImpl.setRa_sau_chieu(getRa_sau_chieu());
		calamviecImpl.setGio_vao_toi(getGio_vao_toi());
		calamviecImpl.setGio_ra_toi(getGio_ra_toi());
		calamviecImpl.setVao_truoc_toi(getVao_truoc_toi());
		calamviecImpl.setRa_sau_toi(getRa_sau_toi());
		calamviecImpl.setGio_vao_sang(getGio_vao_sang());
		calamviecImpl.setGio_ra_sang(getGio_ra_sang());
		calamviecImpl.setVao_truoc_sang(getVao_truoc_sang());
		calamviecImpl.setRa_sau_sang(getRa_sau_sang());
		calamviecImpl.setCreated_at(getCreated_at());
		calamviecImpl.setUpdated_at(getUpdated_at());

		calamviecImpl.resetOriginalValues();

		return calamviecImpl;
	}

	@Override
	public Calamviec cloneWithOriginalValues() {
		CalamviecImpl calamviecImpl = new CalamviecImpl();

		calamviecImpl.setId(this.<Integer>getColumnOriginalValue("id_"));
		calamviecImpl.setTencalamviec(
			this.<String>getColumnOriginalValue("tencalamviec"));
		calamviecImpl.setGio_vao_chieu(
			this.<String>getColumnOriginalValue("gio_vao_chieu"));
		calamviecImpl.setGio_ra_chieu(
			this.<String>getColumnOriginalValue("gio_ra_chieu"));
		calamviecImpl.setVao_truoc_chieu(
			this.<Integer>getColumnOriginalValue("vao_truoc_chieu"));
		calamviecImpl.setRa_sau_chieu(
			this.<Integer>getColumnOriginalValue("ra_sau_chieu"));
		calamviecImpl.setGio_vao_toi(
			this.<String>getColumnOriginalValue("gio_vao_toi"));
		calamviecImpl.setGio_ra_toi(
			this.<String>getColumnOriginalValue("gio_ra_toi"));
		calamviecImpl.setVao_truoc_toi(
			this.<Integer>getColumnOriginalValue("vao_truoc_toi"));
		calamviecImpl.setRa_sau_toi(
			this.<Integer>getColumnOriginalValue("ra_sau_toi"));
		calamviecImpl.setGio_vao_sang(
			this.<String>getColumnOriginalValue("gio_vao_sang"));
		calamviecImpl.setGio_ra_sang(
			this.<String>getColumnOriginalValue("gio_ra_sang"));
		calamviecImpl.setVao_truoc_sang(
			this.<Integer>getColumnOriginalValue("vao_truoc_sang"));
		calamviecImpl.setRa_sau_sang(
			this.<Integer>getColumnOriginalValue("ra_sau_sang"));
		calamviecImpl.setCreated_at(
			this.<Date>getColumnOriginalValue("created_at"));
		calamviecImpl.setUpdated_at(
			this.<Date>getColumnOriginalValue("updated_at"));

		return calamviecImpl;
	}

	@Override
	public int compareTo(Calamviec calamviec) {
		int primaryKey = calamviec.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Calamviec)) {
			return false;
		}

		Calamviec calamviec = (Calamviec)object;

		int primaryKey = calamviec.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Calamviec> toCacheModel() {
		CalamviecCacheModel calamviecCacheModel = new CalamviecCacheModel();

		calamviecCacheModel.id = getId();

		calamviecCacheModel.tencalamviec = getTencalamviec();

		String tencalamviec = calamviecCacheModel.tencalamviec;

		if ((tencalamviec != null) && (tencalamviec.length() == 0)) {
			calamviecCacheModel.tencalamviec = null;
		}

		calamviecCacheModel.gio_vao_chieu = getGio_vao_chieu();

		String gio_vao_chieu = calamviecCacheModel.gio_vao_chieu;

		if ((gio_vao_chieu != null) && (gio_vao_chieu.length() == 0)) {
			calamviecCacheModel.gio_vao_chieu = null;
		}

		calamviecCacheModel.gio_ra_chieu = getGio_ra_chieu();

		String gio_ra_chieu = calamviecCacheModel.gio_ra_chieu;

		if ((gio_ra_chieu != null) && (gio_ra_chieu.length() == 0)) {
			calamviecCacheModel.gio_ra_chieu = null;
		}

		calamviecCacheModel.vao_truoc_chieu = getVao_truoc_chieu();

		calamviecCacheModel.ra_sau_chieu = getRa_sau_chieu();

		calamviecCacheModel.gio_vao_toi = getGio_vao_toi();

		String gio_vao_toi = calamviecCacheModel.gio_vao_toi;

		if ((gio_vao_toi != null) && (gio_vao_toi.length() == 0)) {
			calamviecCacheModel.gio_vao_toi = null;
		}

		calamviecCacheModel.gio_ra_toi = getGio_ra_toi();

		String gio_ra_toi = calamviecCacheModel.gio_ra_toi;

		if ((gio_ra_toi != null) && (gio_ra_toi.length() == 0)) {
			calamviecCacheModel.gio_ra_toi = null;
		}

		calamviecCacheModel.vao_truoc_toi = getVao_truoc_toi();

		calamviecCacheModel.ra_sau_toi = getRa_sau_toi();

		calamviecCacheModel.gio_vao_sang = getGio_vao_sang();

		String gio_vao_sang = calamviecCacheModel.gio_vao_sang;

		if ((gio_vao_sang != null) && (gio_vao_sang.length() == 0)) {
			calamviecCacheModel.gio_vao_sang = null;
		}

		calamviecCacheModel.gio_ra_sang = getGio_ra_sang();

		String gio_ra_sang = calamviecCacheModel.gio_ra_sang;

		if ((gio_ra_sang != null) && (gio_ra_sang.length() == 0)) {
			calamviecCacheModel.gio_ra_sang = null;
		}

		calamviecCacheModel.vao_truoc_sang = getVao_truoc_sang();

		calamviecCacheModel.ra_sau_sang = getRa_sau_sang();

		Date created_at = getCreated_at();

		if (created_at != null) {
			calamviecCacheModel.created_at = created_at.getTime();
		}
		else {
			calamviecCacheModel.created_at = Long.MIN_VALUE;
		}

		Date updated_at = getUpdated_at();

		if (updated_at != null) {
			calamviecCacheModel.updated_at = updated_at.getTime();
		}
		else {
			calamviecCacheModel.updated_at = Long.MIN_VALUE;
		}

		return calamviecCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Calamviec, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Calamviec, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Calamviec, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Calamviec)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Calamviec, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Calamviec, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Calamviec, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Calamviec)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Calamviec>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Calamviec.class, ModelWrapper.class);

	}

	private int _id;
	private String _tencalamviec;
	private String _gio_vao_chieu;
	private String _gio_ra_chieu;
	private int _vao_truoc_chieu;
	private int _ra_sau_chieu;
	private String _gio_vao_toi;
	private String _gio_ra_toi;
	private int _vao_truoc_toi;
	private int _ra_sau_toi;
	private String _gio_vao_sang;
	private String _gio_ra_sang;
	private int _vao_truoc_sang;
	private int _ra_sau_sang;
	private Date _created_at;
	private Date _updated_at;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Calamviec, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Calamviec)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("tencalamviec", _tencalamviec);
		_columnOriginalValues.put("gio_vao_chieu", _gio_vao_chieu);
		_columnOriginalValues.put("gio_ra_chieu", _gio_ra_chieu);
		_columnOriginalValues.put("vao_truoc_chieu", _vao_truoc_chieu);
		_columnOriginalValues.put("ra_sau_chieu", _ra_sau_chieu);
		_columnOriginalValues.put("gio_vao_toi", _gio_vao_toi);
		_columnOriginalValues.put("gio_ra_toi", _gio_ra_toi);
		_columnOriginalValues.put("vao_truoc_toi", _vao_truoc_toi);
		_columnOriginalValues.put("ra_sau_toi", _ra_sau_toi);
		_columnOriginalValues.put("gio_vao_sang", _gio_vao_sang);
		_columnOriginalValues.put("gio_ra_sang", _gio_ra_sang);
		_columnOriginalValues.put("vao_truoc_sang", _vao_truoc_sang);
		_columnOriginalValues.put("ra_sau_sang", _ra_sau_sang);
		_columnOriginalValues.put("created_at", _created_at);
		_columnOriginalValues.put("updated_at", _updated_at);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("tencalamviec", 2L);

		columnBitmasks.put("gio_vao_chieu", 4L);

		columnBitmasks.put("gio_ra_chieu", 8L);

		columnBitmasks.put("vao_truoc_chieu", 16L);

		columnBitmasks.put("ra_sau_chieu", 32L);

		columnBitmasks.put("gio_vao_toi", 64L);

		columnBitmasks.put("gio_ra_toi", 128L);

		columnBitmasks.put("vao_truoc_toi", 256L);

		columnBitmasks.put("ra_sau_toi", 512L);

		columnBitmasks.put("gio_vao_sang", 1024L);

		columnBitmasks.put("gio_ra_sang", 2048L);

		columnBitmasks.put("vao_truoc_sang", 4096L);

		columnBitmasks.put("ra_sau_sang", 8192L);

		columnBitmasks.put("created_at", 16384L);

		columnBitmasks.put("updated_at", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Calamviec _escapedModel;

}