/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.chamcong.model.impl;

import com.liferay.docs.chamcong.model.Ngaynghile;
import com.liferay.docs.chamcong.model.NgaynghileModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Ngaynghile service. Represents a row in the &quot;_Ngaynghile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NgaynghileModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NgaynghileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NgaynghileImpl
 * @generated
 */
@JSON(strict = true)
public class NgaynghileModelImpl
	extends BaseModelImpl<Ngaynghile> implements NgaynghileModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ngaynghile model instance should use the <code>Ngaynghile</code> interface instead.
	 */
	public static final String TABLE_NAME = "_Ngaynghile";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.INTEGER}, {"ten", Types.VARCHAR},
		{"ngay_nghi", Types.TIMESTAMP}, {"trangthai", Types.INTEGER},
		{"created_at", Types.TIMESTAMP}, {"updated_at", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("ten", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ngay_nghi", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("trangthai", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table _Ngaynghile (id_ INTEGER not null primary key,ten VARCHAR(75) null,ngay_nghi DATE null,trangthai INTEGER,created_at DATE null,updated_at DATE null)";

	public static final String TABLE_SQL_DROP = "drop table _Ngaynghile";

	public static final String ORDER_BY_JPQL = " ORDER BY ngaynghile.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY _Ngaynghile.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public NgaynghileModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Ngaynghile.class;
	}

	@Override
	public String getModelClassName() {
		return Ngaynghile.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Ngaynghile, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Ngaynghile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ngaynghile, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Ngaynghile)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Ngaynghile, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Ngaynghile, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Ngaynghile)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Ngaynghile, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Ngaynghile, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Ngaynghile, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Ngaynghile, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Ngaynghile, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Ngaynghile, Object>>();
		Map<String, BiConsumer<Ngaynghile, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Ngaynghile, ?>>();

		attributeGetterFunctions.put("id", Ngaynghile::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<Ngaynghile, Integer>)Ngaynghile::setId);
		attributeGetterFunctions.put("ten", Ngaynghile::getTen);
		attributeSetterBiConsumers.put(
			"ten", (BiConsumer<Ngaynghile, String>)Ngaynghile::setTen);
		attributeGetterFunctions.put("ngay_nghi", Ngaynghile::getNgay_nghi);
		attributeSetterBiConsumers.put(
			"ngay_nghi",
			(BiConsumer<Ngaynghile, Date>)Ngaynghile::setNgay_nghi);
		attributeGetterFunctions.put("trangthai", Ngaynghile::getTrangthai);
		attributeSetterBiConsumers.put(
			"trangthai",
			(BiConsumer<Ngaynghile, Integer>)Ngaynghile::setTrangthai);
		attributeGetterFunctions.put("created_at", Ngaynghile::getCreated_at);
		attributeSetterBiConsumers.put(
			"created_at",
			(BiConsumer<Ngaynghile, Date>)Ngaynghile::setCreated_at);
		attributeGetterFunctions.put("updated_at", Ngaynghile::getUpdated_at);
		attributeSetterBiConsumers.put(
			"updated_at",
			(BiConsumer<Ngaynghile, Date>)Ngaynghile::setUpdated_at);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public int getOriginalId() {
		return GetterUtil.getInteger(
			this.<Integer>getColumnOriginalValue("id_"));
	}

	@JSON
	@Override
	public String getTen() {
		if (_ten == null) {
			return "";
		}
		else {
			return _ten;
		}
	}

	@Override
	public void setTen(String ten) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ten = ten;
	}

	@JSON
	@Override
	public Date getNgay_nghi() {
		return _ngay_nghi;
	}

	@Override
	public void setNgay_nghi(Date ngay_nghi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ngay_nghi = ngay_nghi;
	}

	@JSON
	@Override
	public int getTrangthai() {
		return _trangthai;
	}

	@Override
	public void setTrangthai(int trangthai) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_trangthai = trangthai;
	}

	@JSON
	@Override
	public Date getCreated_at() {
		return _created_at;
	}

	@Override
	public void setCreated_at(Date created_at) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_created_at = created_at;
	}

	@JSON
	@Override
	public Date getUpdated_at() {
		return _updated_at;
	}

	@Override
	public void setUpdated_at(Date updated_at) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updated_at = updated_at;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Ngaynghile toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Ngaynghile>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NgaynghileImpl ngaynghileImpl = new NgaynghileImpl();

		ngaynghileImpl.setId(getId());
		ngaynghileImpl.setTen(getTen());
		ngaynghileImpl.setNgay_nghi(getNgay_nghi());
		ngaynghileImpl.setTrangthai(getTrangthai());
		ngaynghileImpl.setCreated_at(getCreated_at());
		ngaynghileImpl.setUpdated_at(getUpdated_at());

		ngaynghileImpl.resetOriginalValues();

		return ngaynghileImpl;
	}

	@Override
	public Ngaynghile cloneWithOriginalValues() {
		NgaynghileImpl ngaynghileImpl = new NgaynghileImpl();

		ngaynghileImpl.setId(this.<Integer>getColumnOriginalValue("id_"));
		ngaynghileImpl.setTen(this.<String>getColumnOriginalValue("ten"));
		ngaynghileImpl.setNgay_nghi(
			this.<Date>getColumnOriginalValue("ngay_nghi"));
		ngaynghileImpl.setTrangthai(
			this.<Integer>getColumnOriginalValue("trangthai"));
		ngaynghileImpl.setCreated_at(
			this.<Date>getColumnOriginalValue("created_at"));
		ngaynghileImpl.setUpdated_at(
			this.<Date>getColumnOriginalValue("updated_at"));

		return ngaynghileImpl;
	}

	@Override
	public int compareTo(Ngaynghile ngaynghile) {
		int primaryKey = ngaynghile.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Ngaynghile)) {
			return false;
		}

		Ngaynghile ngaynghile = (Ngaynghile)object;

		int primaryKey = ngaynghile.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Ngaynghile> toCacheModel() {
		NgaynghileCacheModel ngaynghileCacheModel = new NgaynghileCacheModel();

		ngaynghileCacheModel.id = getId();

		ngaynghileCacheModel.ten = getTen();

		String ten = ngaynghileCacheModel.ten;

		if ((ten != null) && (ten.length() == 0)) {
			ngaynghileCacheModel.ten = null;
		}

		Date ngay_nghi = getNgay_nghi();

		if (ngay_nghi != null) {
			ngaynghileCacheModel.ngay_nghi = ngay_nghi.getTime();
		}
		else {
			ngaynghileCacheModel.ngay_nghi = Long.MIN_VALUE;
		}

		ngaynghileCacheModel.trangthai = getTrangthai();

		Date created_at = getCreated_at();

		if (created_at != null) {
			ngaynghileCacheModel.created_at = created_at.getTime();
		}
		else {
			ngaynghileCacheModel.created_at = Long.MIN_VALUE;
		}

		Date updated_at = getUpdated_at();

		if (updated_at != null) {
			ngaynghileCacheModel.updated_at = updated_at.getTime();
		}
		else {
			ngaynghileCacheModel.updated_at = Long.MIN_VALUE;
		}

		return ngaynghileCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Ngaynghile, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Ngaynghile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ngaynghile, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Ngaynghile)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Ngaynghile, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Ngaynghile, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Ngaynghile, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Ngaynghile)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Ngaynghile>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Ngaynghile.class, ModelWrapper.class);

	}

	private int _id;
	private String _ten;
	private Date _ngay_nghi;
	private int _trangthai;
	private Date _created_at;
	private Date _updated_at;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Ngaynghile, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Ngaynghile)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("ten", _ten);
		_columnOriginalValues.put("ngay_nghi", _ngay_nghi);
		_columnOriginalValues.put("trangthai", _trangthai);
		_columnOriginalValues.put("created_at", _created_at);
		_columnOriginalValues.put("updated_at", _updated_at);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("ten", 2L);

		columnBitmasks.put("ngay_nghi", 4L);

		columnBitmasks.put("trangthai", 8L);

		columnBitmasks.put("created_at", 16L);

		columnBitmasks.put("updated_at", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Ngaynghile _escapedModel;

}