/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.chamcong.model.impl;

import com.liferay.docs.chamcong.model.Phongban;
import com.liferay.docs.chamcong.model.PhongbanModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Phongban service. Represents a row in the &quot;_Phongban&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PhongbanModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PhongbanImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PhongbanImpl
 * @generated
 */
@JSON(strict = true)
public class PhongbanModelImpl
	extends BaseModelImpl<Phongban> implements PhongbanModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a phongban model instance should use the <code>Phongban</code> interface instead.
	 */
	public static final String TABLE_NAME = "_Phongban";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_", Types.INTEGER}, {"tenphong", Types.VARCHAR},
		{"trangthai", Types.INTEGER}, {"nguoi_phu_trach", Types.INTEGER},
		{"created_at", Types.TIMESTAMP}, {"updated_at", Types.TIMESTAMP},
		{"groupId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("tenphong", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("trangthai", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("nguoi_phu_trach", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("created_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("updated_at", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table _Phongban (id_ INTEGER not null primary key,tenphong VARCHAR(75) null,trangthai INTEGER,nguoi_phu_trach INTEGER,created_at DATE null,updated_at DATE null,groupId LONG)";

	public static final String TABLE_SQL_DROP = "drop table _Phongban";

	public static final String ORDER_BY_JPQL = " ORDER BY phongban.id ASC";

	public static final String ORDER_BY_SQL = " ORDER BY _Phongban.id_ ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PhongbanModelImpl() {
	}

	@Override
	public int getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(int primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Integer)primaryKeyObj).intValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Phongban.class;
	}

	@Override
	public String getModelClassName() {
		return Phongban.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Phongban, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Phongban, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Phongban, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Phongban)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Phongban, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Phongban, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Phongban)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Phongban, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Phongban, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Phongban, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Phongban, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Phongban, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Phongban, Object>>();
		Map<String, BiConsumer<Phongban, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Phongban, ?>>();

		attributeGetterFunctions.put("id", Phongban::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<Phongban, Integer>)Phongban::setId);
		attributeGetterFunctions.put("tenphong", Phongban::getTenphong);
		attributeSetterBiConsumers.put(
			"tenphong", (BiConsumer<Phongban, String>)Phongban::setTenphong);
		attributeGetterFunctions.put("trangthai", Phongban::getTrangthai);
		attributeSetterBiConsumers.put(
			"trangthai", (BiConsumer<Phongban, Integer>)Phongban::setTrangthai);
		attributeGetterFunctions.put(
			"nguoi_phu_trach", Phongban::getNguoi_phu_trach);
		attributeSetterBiConsumers.put(
			"nguoi_phu_trach",
			(BiConsumer<Phongban, Integer>)Phongban::setNguoi_phu_trach);
		attributeGetterFunctions.put("created_at", Phongban::getCreated_at);
		attributeSetterBiConsumers.put(
			"created_at", (BiConsumer<Phongban, Date>)Phongban::setCreated_at);
		attributeGetterFunctions.put("updated_at", Phongban::getUpdated_at);
		attributeSetterBiConsumers.put(
			"updated_at", (BiConsumer<Phongban, Date>)Phongban::setUpdated_at);
		attributeGetterFunctions.put("groupId", Phongban::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Phongban, Long>)Phongban::setGroupId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public int getId() {
		return _id;
	}

	@Override
	public void setId(int id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public String getTenphong() {
		if (_tenphong == null) {
			return "";
		}
		else {
			return _tenphong;
		}
	}

	@Override
	public void setTenphong(String tenphong) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tenphong = tenphong;
	}

	@JSON
	@Override
	public int getTrangthai() {
		return _trangthai;
	}

	@Override
	public void setTrangthai(int trangthai) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_trangthai = trangthai;
	}

	@JSON
	@Override
	public int getNguoi_phu_trach() {
		return _nguoi_phu_trach;
	}

	@Override
	public void setNguoi_phu_trach(int nguoi_phu_trach) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nguoi_phu_trach = nguoi_phu_trach;
	}

	@JSON
	@Override
	public Date getCreated_at() {
		return _created_at;
	}

	@Override
	public void setCreated_at(Date created_at) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_created_at = created_at;
	}

	@JSON
	@Override
	public Date getUpdated_at() {
		return _updated_at;
	}

	@Override
	public void setUpdated_at(Date updated_at) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_updated_at = updated_at;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public Phongban toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Phongban>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PhongbanImpl phongbanImpl = new PhongbanImpl();

		phongbanImpl.setId(getId());
		phongbanImpl.setTenphong(getTenphong());
		phongbanImpl.setTrangthai(getTrangthai());
		phongbanImpl.setNguoi_phu_trach(getNguoi_phu_trach());
		phongbanImpl.setCreated_at(getCreated_at());
		phongbanImpl.setUpdated_at(getUpdated_at());
		phongbanImpl.setGroupId(getGroupId());

		phongbanImpl.resetOriginalValues();

		return phongbanImpl;
	}

	@Override
	public Phongban cloneWithOriginalValues() {
		PhongbanImpl phongbanImpl = new PhongbanImpl();

		phongbanImpl.setId(this.<Integer>getColumnOriginalValue("id_"));
		phongbanImpl.setTenphong(
			this.<String>getColumnOriginalValue("tenphong"));
		phongbanImpl.setTrangthai(
			this.<Integer>getColumnOriginalValue("trangthai"));
		phongbanImpl.setNguoi_phu_trach(
			this.<Integer>getColumnOriginalValue("nguoi_phu_trach"));
		phongbanImpl.setCreated_at(
			this.<Date>getColumnOriginalValue("created_at"));
		phongbanImpl.setUpdated_at(
			this.<Date>getColumnOriginalValue("updated_at"));
		phongbanImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));

		return phongbanImpl;
	}

	@Override
	public int compareTo(Phongban phongban) {
		int primaryKey = phongban.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Phongban)) {
			return false;
		}

		Phongban phongban = (Phongban)object;

		int primaryKey = phongban.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Phongban> toCacheModel() {
		PhongbanCacheModel phongbanCacheModel = new PhongbanCacheModel();

		phongbanCacheModel.id = getId();

		phongbanCacheModel.tenphong = getTenphong();

		String tenphong = phongbanCacheModel.tenphong;

		if ((tenphong != null) && (tenphong.length() == 0)) {
			phongbanCacheModel.tenphong = null;
		}

		phongbanCacheModel.trangthai = getTrangthai();

		phongbanCacheModel.nguoi_phu_trach = getNguoi_phu_trach();

		Date created_at = getCreated_at();

		if (created_at != null) {
			phongbanCacheModel.created_at = created_at.getTime();
		}
		else {
			phongbanCacheModel.created_at = Long.MIN_VALUE;
		}

		Date updated_at = getUpdated_at();

		if (updated_at != null) {
			phongbanCacheModel.updated_at = updated_at.getTime();
		}
		else {
			phongbanCacheModel.updated_at = Long.MIN_VALUE;
		}

		phongbanCacheModel.groupId = getGroupId();

		return phongbanCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Phongban, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Phongban, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Phongban, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Phongban)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Phongban, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Phongban, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Phongban, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Phongban)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Phongban>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Phongban.class, ModelWrapper.class);

	}

	private int _id;
	private String _tenphong;
	private int _trangthai;
	private int _nguoi_phu_trach;
	private Date _created_at;
	private Date _updated_at;
	private long _groupId;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Phongban, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Phongban)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("tenphong", _tenphong);
		_columnOriginalValues.put("trangthai", _trangthai);
		_columnOriginalValues.put("nguoi_phu_trach", _nguoi_phu_trach);
		_columnOriginalValues.put("created_at", _created_at);
		_columnOriginalValues.put("updated_at", _updated_at);
		_columnOriginalValues.put("groupId", _groupId);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("id_", 1L);

		columnBitmasks.put("tenphong", 2L);

		columnBitmasks.put("trangthai", 4L);

		columnBitmasks.put("nguoi_phu_trach", 8L);

		columnBitmasks.put("created_at", 16L);

		columnBitmasks.put("updated_at", 32L);

		columnBitmasks.put("groupId", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Phongban _escapedModel;

}