/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.chamcong.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Chucvu service. Represents a row in the &quot;_Chucvu&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.docs.chamcong.model.impl.ChucvuModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.docs.chamcong.model.impl.ChucvuImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Chucvu
 * @generated
 */
@ProviderType
public interface ChucvuModel extends BaseModel<Chucvu> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a chucvu model instance should use the {@link Chucvu} interface instead.
	 */

	/**
	 * Returns the primary key of this chucvu.
	 *
	 * @return the primary key of this chucvu
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this chucvu.
	 *
	 * @param primaryKey the primary key of this chucvu
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this chucvu.
	 *
	 * @return the ID of this chucvu
	 */
	public int getId();

	/**
	 * Sets the ID of this chucvu.
	 *
	 * @param id the ID of this chucvu
	 */
	public void setId(int id);

	/**
	 * Returns the name of this chucvu.
	 *
	 * @return the name of this chucvu
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this chucvu.
	 *
	 * @param name the name of this chucvu
	 */
	public void setName(String name);

	/**
	 * Returns the created_at of this chucvu.
	 *
	 * @return the created_at of this chucvu
	 */
	public Date getCreated_at();

	/**
	 * Sets the created_at of this chucvu.
	 *
	 * @param created_at the created_at of this chucvu
	 */
	public void setCreated_at(Date created_at);

	/**
	 * Returns the updated_at of this chucvu.
	 *
	 * @return the updated_at of this chucvu
	 */
	public Date getUpdated_at();

	/**
	 * Sets the updated_at of this chucvu.
	 *
	 * @param updated_at the updated_at of this chucvu
	 */
	public void setUpdated_at(Date updated_at);

	/**
	 * Returns the role of this chucvu.
	 *
	 * @return the role of this chucvu
	 */
	public int getRole();

	/**
	 * Sets the role of this chucvu.
	 *
	 * @param role the role of this chucvu
	 */
	public void setRole(int role);

	/**
	 * Returns the group ID of this chucvu.
	 *
	 * @return the group ID of this chucvu
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this chucvu.
	 *
	 * @param groupId the group ID of this chucvu
	 */
	public void setGroupId(long groupId);

	@Override
	public Chucvu cloneWithOriginalValues();

}