/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.chamcong.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Filekyso service. Represents a row in the &quot;_Filekyso&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.docs.chamcong.model.impl.FilekysoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.docs.chamcong.model.impl.FilekysoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Filekyso
 * @generated
 */
@ProviderType
public interface FilekysoModel extends BaseModel<Filekyso> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a filekyso model instance should use the {@link Filekyso} interface instead.
	 */

	/**
	 * Returns the primary key of this filekyso.
	 *
	 * @return the primary key of this filekyso
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this filekyso.
	 *
	 * @param primaryKey the primary key of this filekyso
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this filekyso.
	 *
	 * @return the ID of this filekyso
	 */
	public int getId();

	/**
	 * Sets the ID of this filekyso.
	 *
	 * @param id the ID of this filekyso
	 */
	public void setId(int id);

	/**
	 * Returns the tenfile of this filekyso.
	 *
	 * @return the tenfile of this filekyso
	 */
	@AutoEscape
	public String getTenfile();

	/**
	 * Sets the tenfile of this filekyso.
	 *
	 * @param tenfile the tenfile of this filekyso
	 */
	public void setTenfile(String tenfile);

	@Override
	public Filekyso cloneWithOriginalValues();

}