/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.chamcong.model;

import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Ngaylamviec service. Represents a row in the &quot;_Ngaylamviec&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.docs.chamcong.model.impl.NgaylamviecModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.docs.chamcong.model.impl.NgaylamviecImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Ngaylamviec
 * @generated
 */
@ProviderType
public interface NgaylamviecModel extends BaseModel<Ngaylamviec> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ngaylamviec model instance should use the {@link Ngaylamviec} interface instead.
	 */

	/**
	 * Returns the primary key of this ngaylamviec.
	 *
	 * @return the primary key of this ngaylamviec
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this ngaylamviec.
	 *
	 * @param primaryKey the primary key of this ngaylamviec
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this ngaylamviec.
	 *
	 * @return the ID of this ngaylamviec
	 */
	public int getId();

	/**
	 * Sets the ID of this ngaylamviec.
	 *
	 * @param id the ID of this ngaylamviec
	 */
	public void setId(int id);

	/**
	 * Returns the nam of this ngaylamviec.
	 *
	 * @return the nam of this ngaylamviec
	 */
	public int getNam();

	/**
	 * Sets the nam of this ngaylamviec.
	 *
	 * @param nam the nam of this ngaylamviec
	 */
	public void setNam(int nam);

	/**
	 * Returns the thang of this ngaylamviec.
	 *
	 * @return the thang of this ngaylamviec
	 */
	public int getThang();

	/**
	 * Sets the thang of this ngaylamviec.
	 *
	 * @param thang the thang of this ngaylamviec
	 */
	public void setThang(int thang);

	/**
	 * Returns the so_ngay_lam_viec of this ngaylamviec.
	 *
	 * @return the so_ngay_lam_viec of this ngaylamviec
	 */
	public int getSo_ngay_lam_viec();

	/**
	 * Sets the so_ngay_lam_viec of this ngaylamviec.
	 *
	 * @param so_ngay_lam_viec the so_ngay_lam_viec of this ngaylamviec
	 */
	public void setSo_ngay_lam_viec(int so_ngay_lam_viec);

	/**
	 * Returns the trangthai of this ngaylamviec.
	 *
	 * @return the trangthai of this ngaylamviec
	 */
	public int getTrangthai();

	/**
	 * Sets the trangthai of this ngaylamviec.
	 *
	 * @param trangthai the trangthai of this ngaylamviec
	 */
	public void setTrangthai(int trangthai);

	/**
	 * Returns the created_at of this ngaylamviec.
	 *
	 * @return the created_at of this ngaylamviec
	 */
	public Date getCreated_at();

	/**
	 * Sets the created_at of this ngaylamviec.
	 *
	 * @param created_at the created_at of this ngaylamviec
	 */
	public void setCreated_at(Date created_at);

	/**
	 * Returns the updated_at of this ngaylamviec.
	 *
	 * @return the updated_at of this ngaylamviec
	 */
	public Date getUpdated_at();

	/**
	 * Sets the updated_at of this ngaylamviec.
	 *
	 * @param updated_at the updated_at of this ngaylamviec
	 */
	public void setUpdated_at(Date updated_at);

	@Override
	public Ngaylamviec cloneWithOriginalValues();

}