/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.chamcong.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Ngaynghile service. Represents a row in the &quot;_Ngaynghile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.docs.chamcong.model.impl.NgaynghileModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.docs.chamcong.model.impl.NgaynghileImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Ngaynghile
 * @generated
 */
@ProviderType
public interface NgaynghileModel extends BaseModel<Ngaynghile> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ngaynghile model instance should use the {@link Ngaynghile} interface instead.
	 */

	/**
	 * Returns the primary key of this ngaynghile.
	 *
	 * @return the primary key of this ngaynghile
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this ngaynghile.
	 *
	 * @param primaryKey the primary key of this ngaynghile
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this ngaynghile.
	 *
	 * @return the ID of this ngaynghile
	 */
	public int getId();

	/**
	 * Sets the ID of this ngaynghile.
	 *
	 * @param id the ID of this ngaynghile
	 */
	public void setId(int id);

	/**
	 * Returns the ten of this ngaynghile.
	 *
	 * @return the ten of this ngaynghile
	 */
	@AutoEscape
	public String getTen();

	/**
	 * Sets the ten of this ngaynghile.
	 *
	 * @param ten the ten of this ngaynghile
	 */
	public void setTen(String ten);

	/**
	 * Returns the ngay_nghi of this ngaynghile.
	 *
	 * @return the ngay_nghi of this ngaynghile
	 */
	public Date getNgay_nghi();

	/**
	 * Sets the ngay_nghi of this ngaynghile.
	 *
	 * @param ngay_nghi the ngay_nghi of this ngaynghile
	 */
	public void setNgay_nghi(Date ngay_nghi);

	/**
	 * Returns the trangthai of this ngaynghile.
	 *
	 * @return the trangthai of this ngaynghile
	 */
	public int getTrangthai();

	/**
	 * Sets the trangthai of this ngaynghile.
	 *
	 * @param trangthai the trangthai of this ngaynghile
	 */
	public void setTrangthai(int trangthai);

	/**
	 * Returns the created_at of this ngaynghile.
	 *
	 * @return the created_at of this ngaynghile
	 */
	public Date getCreated_at();

	/**
	 * Sets the created_at of this ngaynghile.
	 *
	 * @param created_at the created_at of this ngaynghile
	 */
	public void setCreated_at(Date created_at);

	/**
	 * Returns the updated_at of this ngaynghile.
	 *
	 * @return the updated_at of this ngaynghile
	 */
	public Date getUpdated_at();

	/**
	 * Sets the updated_at of this ngaynghile.
	 *
	 * @param updated_at the updated_at of this ngaynghile
	 */
	public void setUpdated_at(Date updated_at);

	@Override
	public Ngaynghile cloneWithOriginalValues();

}