/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.chamcong.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Phongban service. Represents a row in the &quot;_Phongban&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.docs.chamcong.model.impl.PhongbanModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.docs.chamcong.model.impl.PhongbanImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Phongban
 * @generated
 */
@ProviderType
public interface PhongbanModel extends BaseModel<Phongban> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a phongban model instance should use the {@link Phongban} interface instead.
	 */

	/**
	 * Returns the primary key of this phongban.
	 *
	 * @return the primary key of this phongban
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this phongban.
	 *
	 * @param primaryKey the primary key of this phongban
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this phongban.
	 *
	 * @return the ID of this phongban
	 */
	public int getId();

	/**
	 * Sets the ID of this phongban.
	 *
	 * @param id the ID of this phongban
	 */
	public void setId(int id);

	/**
	 * Returns the tenphong of this phongban.
	 *
	 * @return the tenphong of this phongban
	 */
	@AutoEscape
	public String getTenphong();

	/**
	 * Sets the tenphong of this phongban.
	 *
	 * @param tenphong the tenphong of this phongban
	 */
	public void setTenphong(String tenphong);

	/**
	 * Returns the trangthai of this phongban.
	 *
	 * @return the trangthai of this phongban
	 */
	public int getTrangthai();

	/**
	 * Sets the trangthai of this phongban.
	 *
	 * @param trangthai the trangthai of this phongban
	 */
	public void setTrangthai(int trangthai);

	/**
	 * Returns the nguoi_phu_trach of this phongban.
	 *
	 * @return the nguoi_phu_trach of this phongban
	 */
	public int getNguoi_phu_trach();

	/**
	 * Sets the nguoi_phu_trach of this phongban.
	 *
	 * @param nguoi_phu_trach the nguoi_phu_trach of this phongban
	 */
	public void setNguoi_phu_trach(int nguoi_phu_trach);

	/**
	 * Returns the created_at of this phongban.
	 *
	 * @return the created_at of this phongban
	 */
	public Date getCreated_at();

	/**
	 * Sets the created_at of this phongban.
	 *
	 * @param created_at the created_at of this phongban
	 */
	public void setCreated_at(Date created_at);

	/**
	 * Returns the updated_at of this phongban.
	 *
	 * @return the updated_at of this phongban
	 */
	public Date getUpdated_at();

	/**
	 * Sets the updated_at of this phongban.
	 *
	 * @param updated_at the updated_at of this phongban
	 */
	public void setUpdated_at(Date updated_at);

	/**
	 * Returns the group ID of this phongban.
	 *
	 * @return the group ID of this phongban
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this phongban.
	 *
	 * @param groupId the group ID of this phongban
	 */
	public void setGroupId(long groupId);

	@Override
	public Phongban cloneWithOriginalValues();

}