/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.docs.chamcong.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Xinchamcong service. Represents a row in the &quot;_Xinchamcong&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.docs.chamcong.model.impl.XinchamcongModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.docs.chamcong.model.impl.XinchamcongImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Xinchamcong
 * @generated
 */
@ProviderType
public interface XinchamcongModel extends BaseModel<Xinchamcong> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a xinchamcong model instance should use the {@link Xinchamcong} interface instead.
	 */

	/**
	 * Returns the primary key of this xinchamcong.
	 *
	 * @return the primary key of this xinchamcong
	 */
	public int getPrimaryKey();

	/**
	 * Sets the primary key of this xinchamcong.
	 *
	 * @param primaryKey the primary key of this xinchamcong
	 */
	public void setPrimaryKey(int primaryKey);

	/**
	 * Returns the ID of this xinchamcong.
	 *
	 * @return the ID of this xinchamcong
	 */
	public int getId();

	/**
	 * Sets the ID of this xinchamcong.
	 *
	 * @param id the ID of this xinchamcong
	 */
	public void setId(int id);

	/**
	 * Returns the user_id of this xinchamcong.
	 *
	 * @return the user_id of this xinchamcong
	 */
	public long getUser_id();

	/**
	 * Sets the user_id of this xinchamcong.
	 *
	 * @param user_id the user_id of this xinchamcong
	 */
	public void setUser_id(long user_id);

	/**
	 * Returns the ly_do of this xinchamcong.
	 *
	 * @return the ly_do of this xinchamcong
	 */
	@AutoEscape
	public String getLy_do();

	/**
	 * Sets the ly_do of this xinchamcong.
	 *
	 * @param ly_do the ly_do of this xinchamcong
	 */
	public void setLy_do(String ly_do);

	/**
	 * Returns the ca_lam of this xinchamcong.
	 *
	 * @return the ca_lam of this xinchamcong
	 */
	@AutoEscape
	public String getCa_lam();

	/**
	 * Sets the ca_lam of this xinchamcong.
	 *
	 * @param ca_lam the ca_lam of this xinchamcong
	 */
	public void setCa_lam(String ca_lam);

	/**
	 * Returns the check_in of this xinchamcong.
	 *
	 * @return the check_in of this xinchamcong
	 */
	@AutoEscape
	public String getCheck_in();

	/**
	 * Sets the check_in of this xinchamcong.
	 *
	 * @param check_in the check_in of this xinchamcong
	 */
	public void setCheck_in(String check_in);

	/**
	 * Returns the check_out of this xinchamcong.
	 *
	 * @return the check_out of this xinchamcong
	 */
	@AutoEscape
	public String getCheck_out();

	/**
	 * Sets the check_out of this xinchamcong.
	 *
	 * @param check_out the check_out of this xinchamcong
	 */
	public void setCheck_out(String check_out);

	/**
	 * Returns the ngay_lam of this xinchamcong.
	 *
	 * @return the ngay_lam of this xinchamcong
	 */
	public Date getNgay_lam();

	/**
	 * Sets the ngay_lam of this xinchamcong.
	 *
	 * @param ngay_lam the ngay_lam of this xinchamcong
	 */
	public void setNgay_lam(Date ngay_lam);

	/**
	 * Returns the nguoi_duyet of this xinchamcong.
	 *
	 * @return the nguoi_duyet of this xinchamcong
	 */
	public long getNguoi_duyet();

	/**
	 * Sets the nguoi_duyet of this xinchamcong.
	 *
	 * @param nguoi_duyet the nguoi_duyet of this xinchamcong
	 */
	public void setNguoi_duyet(long nguoi_duyet);

	/**
	 * Returns the nguoi_huy of this xinchamcong.
	 *
	 * @return the nguoi_huy of this xinchamcong
	 */
	public long getNguoi_huy();

	/**
	 * Sets the nguoi_huy of this xinchamcong.
	 *
	 * @param nguoi_huy the nguoi_huy of this xinchamcong
	 */
	public void setNguoi_huy(long nguoi_huy);

	/**
	 * Returns the diem of this xinchamcong.
	 *
	 * @return the diem of this xinchamcong
	 */
	public double getDiem();

	/**
	 * Sets the diem of this xinchamcong.
	 *
	 * @param diem the diem of this xinchamcong
	 */
	public void setDiem(double diem);

	/**
	 * Returns the trangthai of this xinchamcong.
	 *
	 * @return the trangthai of this xinchamcong
	 */
	public int getTrangthai();

	/**
	 * Sets the trangthai of this xinchamcong.
	 *
	 * @param trangthai the trangthai of this xinchamcong
	 */
	public void setTrangthai(int trangthai);

	/**
	 * Returns the created_at of this xinchamcong.
	 *
	 * @return the created_at of this xinchamcong
	 */
	public Date getCreated_at();

	/**
	 * Sets the created_at of this xinchamcong.
	 *
	 * @param created_at the created_at of this xinchamcong
	 */
	public void setCreated_at(Date created_at);

	/**
	 * Returns the updated_at of this xinchamcong.
	 *
	 * @return the updated_at of this xinchamcong
	 */
	public Date getUpdated_at();

	/**
	 * Sets the updated_at of this xinchamcong.
	 *
	 * @param updated_at the updated_at of this xinchamcong
	 */
	public void setUpdated_at(Date updated_at);

	/**
	 * Returns the phongban_id of this xinchamcong.
	 *
	 * @return the phongban_id of this xinchamcong
	 */
	public long getPhongban_id();

	/**
	 * Sets the phongban_id of this xinchamcong.
	 *
	 * @param phongban_id the phongban_id of this xinchamcong
	 */
	public void setPhongban_id(long phongban_id);

	@Override
	public Xinchamcong cloneWithOriginalValues();

}